all: interpreter.c
	gcc -Wall interpreter.c -o interpreter

a: interpreter.c
	gcc -Wall interpreter.c -o interpreter

b: interpreter_p.c
	gcc -Wall interpreter_p.c -o interpreter_p

files: a.c b.c c.c
	gcc -Wall a.c -o a
	gcc -Wall b.c -o b
	gcc -Wall c.c -o c



